// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: api/loopback.proto

package loopbackpb

import (
	context "context"
	raftpb "github.com/shadil/raftlite/api/go/raftpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Loopback_AddBlock_FullMethodName = "/raftlite.Loopback/AddBlock"
)

// LoopbackClient is the client API for Loopback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoopbackClient interface {
	AddBlock(ctx context.Context, in *raftpb.AddBlockRequest, opts ...grpc.CallOption) (*raftpb.AddBlockResponse, error)
}

type loopbackClient struct {
	cc grpc.ClientConnInterface
}

func NewLoopbackClient(cc grpc.ClientConnInterface) LoopbackClient {
	return &loopbackClient{cc}
}

func (c *loopbackClient) AddBlock(ctx context.Context, in *raftpb.AddBlockRequest, opts ...grpc.CallOption) (*raftpb.AddBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(raftpb.AddBlockResponse)
	err := c.cc.Invoke(ctx, Loopback_AddBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoopbackServer is the server API for Loopback service.
// All implementations must embed UnimplementedLoopbackServer
// for forward compatibility.
type LoopbackServer interface {
	AddBlock(context.Context, *raftpb.AddBlockRequest) (*raftpb.AddBlockResponse, error)
	mustEmbedUnimplementedLoopbackServer()
}

// UnimplementedLoopbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoopbackServer struct{}

func (UnimplementedLoopbackServer) AddBlock(context.Context, *raftpb.AddBlockRequest) (*raftpb.AddBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlock not implemented")
}
func (UnimplementedLoopbackServer) mustEmbedUnimplementedLoopbackServer() {}
func (UnimplementedLoopbackServer) testEmbeddedByValue()                  {}

// UnsafeLoopbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoopbackServer will
// result in compilation errors.
type UnsafeLoopbackServer interface {
	mustEmbedUnimplementedLoopbackServer()
}

func RegisterLoopbackServer(s grpc.ServiceRegistrar, srv LoopbackServer) {
	// If the following call panics, it indicates UnimplementedLoopbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Loopback_ServiceDesc, srv)
}

func _Loopback_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(raftpb.AddBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoopbackServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loopback_AddBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoopbackServer).AddBlock(ctx, req.(*raftpb.AddBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Loopback_ServiceDesc is the grpc.ServiceDesc for Loopback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Loopback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raftlite.Loopback",
	HandlerType: (*LoopbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlock",
			Handler:    _Loopback_AddBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/loopback.proto",
}
