// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: api/loopback.proto

package loopbackpb

import (
	raftpb "github.com/shadil/raftlite/api/go/raftpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_loopback_proto protoreflect.FileDescriptor

const file_api_loopback_proto_rawDesc = "" +
	"\n" +
	"\x12api/loopback.proto\x12\braftlite\x1a\x0eapi/raft.proto2M\n" +
	"\bLoopback\x12A\n" +
	"\bAddBlock\x12\x19.raftlite.AddBlockRequest\x1a\x1a.raftlite.AddBlockResponseB.Z,github.com/shadil/raftlite/api/go/loopbackpbb\x06proto3"

var file_api_loopback_proto_goTypes = []any{
	(*raftpb.AddBlockRequest)(nil),  // 0: raftlite.AddBlockRequest
	(*raftpb.AddBlockResponse)(nil), // 1: raftlite.AddBlockResponse
}
var file_api_loopback_proto_depIdxs = []int32{
	0, // 0: raftlite.Loopback.AddBlock:input_type -> raftlite.AddBlockRequest
	1, // 1: raftlite.Loopback.AddBlock:output_type -> raftlite.AddBlockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_loopback_proto_init() }
func file_api_loopback_proto_init() {
	if File_api_loopback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_loopback_proto_rawDesc), len(file_api_loopback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_loopback_proto_goTypes,
		DependencyIndexes: file_api_loopback_proto_depIdxs,
	}.Build()
	File_api_loopback_proto = out.File
	file_api_loopback_proto_goTypes = nil
	file_api_loopback_proto_depIdxs = nil
}
